### ISSUE TITLE
MATLAB is launched from $HOME/pw/bootstrap/noVNC-1.3.0

### ISSUE THREAD

**Issue by stefangary** [parallelworks/interactive_session#6]
When the MATLAB interactive session runs on AECM, the starting location of the MATLAB GUI is in `$HOME/pw/bootstrap/noVNC-1.3.0`.  This is confusing to the user because they did not create this directory and it looks unfamiliar.  My guess is that the `matlab` command was invoked from this directory - is it possible to `cd $HOME/pw/` before invoking `matlab` so the user starts in a more familiar location with MATLAB?

**Comment by avidalto** [comment]
Fixed in main
